# Generated by Django 4.0.1 on 2022-07-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblistingtable',
            name='category',
            field=models.CharField(blank=True, choices=[('News', 'News'), ('Entertainment', 'Entertainment'), ('Politics', 'Politics'), ('Dating', 'Dating')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weblistingtable',
            name='country',
            field=models.CharField(blank=True, choices=[('uk', 'uk')], max_length=100, null=True),
        ),
    ]
